FROM  ubuntu:18.04
ENV LANG=en_US.UTF-8

ENV LC_ALL=C
RUN apt-get update

RUN export LC_ALL=Ci
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y -q && apt-get install -y wget \
        net-tools \
        iproute2 \
        git \
        inetutils-ping \
        haproxy \
        python \
        python-yaml \
        curl \
        python3 \
        python3-pip \
        libffi-dev \
        libssl-dev

RUN pip3 install pyyaml
RUN pip3 install netlib

RUN wget "https://github.com/mitmproxy/mitmproxy/releases/download/v4.0.1/mitmproxy-4.0.1-linux.tar.gz" && \
    tar -xvzf mitmproxy-4.0.1-linux.tar.gz  
    #chmod u+x mitmproxy-4.0.1-linux.tar.gz

ADD start.sh start.sh
RUN chmod +x start.sh
ADD stop.sh stop.sh
RUN chmod +x stop.sh
ADD config.yaml ~/.mitmproxy/config.yaml
ADD log_intf_statistics.py log_intf_statistics.py
# ADD sample.py ~/.mitmproxy/sample.py

WORKDIR /

RUN mkdir /tngbench_share
ENTRYPOINT ["./start.sh"]
CMD ["/bin/bash"]



